/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EarningsIndexRouteImport } from './routes/earnings.index'
import { Route as EarningsWalletsRouteImport } from './routes/earnings.wallets'
import { Route as EarningsSettlementsRouteImport } from './routes/earnings.settlements'
import { Route as EarningsPayoutsRouteImport } from './routes/earnings.payouts'
import { Route as EarningsCommissionsRouteImport } from './routes/earnings.commissions'
import { Route as EarningsBookingsRouteImport } from './routes/earnings.bookings'
import { Route as EarningsBookingsIdRouteImport } from './routes/earnings.bookings.$id'

const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsIndexRoute = EarningsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EarningsRoute,
} as any)
const EarningsWalletsRoute = EarningsWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => EarningsRoute,
} as any)
const EarningsSettlementsRoute = EarningsSettlementsRouteImport.update({
  id: '/settlements',
  path: '/settlements',
  getParentRoute: () => EarningsRoute,
} as any)
const EarningsPayoutsRoute = EarningsPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => EarningsRoute,
} as any)
const EarningsCommissionsRoute = EarningsCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => EarningsRoute,
} as any)
const EarningsBookingsRoute = EarningsBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => EarningsRoute,
} as any)
const EarningsBookingsIdRoute = EarningsBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EarningsBookingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/earnings': typeof EarningsRouteWithChildren
  '/earnings/bookings': typeof EarningsBookingsRouteWithChildren
  '/earnings/commissions': typeof EarningsCommissionsRoute
  '/earnings/payouts': typeof EarningsPayoutsRoute
  '/earnings/settlements': typeof EarningsSettlementsRoute
  '/earnings/wallets': typeof EarningsWalletsRoute
  '/earnings/': typeof EarningsIndexRoute
  '/earnings/bookings/$id': typeof EarningsBookingsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/earnings/bookings': typeof EarningsBookingsRouteWithChildren
  '/earnings/commissions': typeof EarningsCommissionsRoute
  '/earnings/payouts': typeof EarningsPayoutsRoute
  '/earnings/settlements': typeof EarningsSettlementsRoute
  '/earnings/wallets': typeof EarningsWalletsRoute
  '/earnings': typeof EarningsIndexRoute
  '/earnings/bookings/$id': typeof EarningsBookingsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/earnings': typeof EarningsRouteWithChildren
  '/earnings/bookings': typeof EarningsBookingsRouteWithChildren
  '/earnings/commissions': typeof EarningsCommissionsRoute
  '/earnings/payouts': typeof EarningsPayoutsRoute
  '/earnings/settlements': typeof EarningsSettlementsRoute
  '/earnings/wallets': typeof EarningsWalletsRoute
  '/earnings/': typeof EarningsIndexRoute
  '/earnings/bookings/$id': typeof EarningsBookingsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/earnings'
    | '/earnings/bookings'
    | '/earnings/commissions'
    | '/earnings/payouts'
    | '/earnings/settlements'
    | '/earnings/wallets'
    | '/earnings/'
    | '/earnings/bookings/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/earnings/bookings'
    | '/earnings/commissions'
    | '/earnings/payouts'
    | '/earnings/settlements'
    | '/earnings/wallets'
    | '/earnings'
    | '/earnings/bookings/$id'
  id:
    | '__root__'
    | '/'
    | '/earnings'
    | '/earnings/bookings'
    | '/earnings/commissions'
    | '/earnings/payouts'
    | '/earnings/settlements'
    | '/earnings/wallets'
    | '/earnings/'
    | '/earnings/bookings/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EarningsRoute: typeof EarningsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings/': {
      id: '/earnings/'
      path: '/'
      fullPath: '/earnings/'
      preLoaderRoute: typeof EarningsIndexRouteImport
      parentRoute: typeof EarningsRoute
    }
    '/earnings/wallets': {
      id: '/earnings/wallets'
      path: '/wallets'
      fullPath: '/earnings/wallets'
      preLoaderRoute: typeof EarningsWalletsRouteImport
      parentRoute: typeof EarningsRoute
    }
    '/earnings/settlements': {
      id: '/earnings/settlements'
      path: '/settlements'
      fullPath: '/earnings/settlements'
      preLoaderRoute: typeof EarningsSettlementsRouteImport
      parentRoute: typeof EarningsRoute
    }
    '/earnings/payouts': {
      id: '/earnings/payouts'
      path: '/payouts'
      fullPath: '/earnings/payouts'
      preLoaderRoute: typeof EarningsPayoutsRouteImport
      parentRoute: typeof EarningsRoute
    }
    '/earnings/commissions': {
      id: '/earnings/commissions'
      path: '/commissions'
      fullPath: '/earnings/commissions'
      preLoaderRoute: typeof EarningsCommissionsRouteImport
      parentRoute: typeof EarningsRoute
    }
    '/earnings/bookings': {
      id: '/earnings/bookings'
      path: '/bookings'
      fullPath: '/earnings/bookings'
      preLoaderRoute: typeof EarningsBookingsRouteImport
      parentRoute: typeof EarningsRoute
    }
    '/earnings/bookings/$id': {
      id: '/earnings/bookings/$id'
      path: '/$id'
      fullPath: '/earnings/bookings/$id'
      preLoaderRoute: typeof EarningsBookingsIdRouteImport
      parentRoute: typeof EarningsBookingsRoute
    }
  }
}

interface EarningsBookingsRouteChildren {
  EarningsBookingsIdRoute: typeof EarningsBookingsIdRoute
}

const EarningsBookingsRouteChildren: EarningsBookingsRouteChildren = {
  EarningsBookingsIdRoute: EarningsBookingsIdRoute,
}

const EarningsBookingsRouteWithChildren =
  EarningsBookingsRoute._addFileChildren(EarningsBookingsRouteChildren)

interface EarningsRouteChildren {
  EarningsBookingsRoute: typeof EarningsBookingsRouteWithChildren
  EarningsCommissionsRoute: typeof EarningsCommissionsRoute
  EarningsPayoutsRoute: typeof EarningsPayoutsRoute
  EarningsSettlementsRoute: typeof EarningsSettlementsRoute
  EarningsWalletsRoute: typeof EarningsWalletsRoute
  EarningsIndexRoute: typeof EarningsIndexRoute
}

const EarningsRouteChildren: EarningsRouteChildren = {
  EarningsBookingsRoute: EarningsBookingsRouteWithChildren,
  EarningsCommissionsRoute: EarningsCommissionsRoute,
  EarningsPayoutsRoute: EarningsPayoutsRoute,
  EarningsSettlementsRoute: EarningsSettlementsRoute,
  EarningsWalletsRoute: EarningsWalletsRoute,
  EarningsIndexRoute: EarningsIndexRoute,
}

const EarningsRouteWithChildren = EarningsRoute._addFileChildren(
  EarningsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EarningsRoute: EarningsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
