/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EarningsIndexRouteImport } from './routes/earnings.index'

const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsIndexRoute = EarningsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EarningsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/earnings': typeof EarningsRouteWithChildren
  '/earnings/': typeof EarningsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/earnings': typeof EarningsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/earnings': typeof EarningsRouteWithChildren
  '/earnings/': typeof EarningsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/earnings' | '/earnings/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/earnings'
  id: '__root__' | '/' | '/earnings' | '/earnings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EarningsRoute: typeof EarningsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings/': {
      id: '/earnings/'
      path: '/'
      fullPath: '/earnings/'
      preLoaderRoute: typeof EarningsIndexRouteImport
      parentRoute: typeof EarningsRoute
    }
  }
}

interface EarningsRouteChildren {
  EarningsIndexRoute: typeof EarningsIndexRoute
}

const EarningsRouteChildren: EarningsRouteChildren = {
  EarningsIndexRoute: EarningsIndexRoute,
}

const EarningsRouteWithChildren = EarningsRoute._addFileChildren(
  EarningsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EarningsRoute: EarningsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
